import { createReadStream } from 'node:fs';
import { mkdir, rm, rmdir, stat } from 'node:fs/promises';
import { Readable } from 'node:stream';
import { dirname, join, resolve, sep } from 'node:path';
import { dataDir } from './config';
import { localDayKey } from '$lib/days';

/**
 * Recordings on local disk under `<data>/audio/`. Keys are relative paths
 * generated by this module, so a key that escapes the audio directory is a bug
 * or an attack and is refused rather than resolved.
 */

export function audioRoot(): string {
	return join(dataDir(), 'audio');
}

/** File extension for a recording's MIME type. Safari has no WebM encoder and falls back to audio/mp4. */
export function audioExtension(contentType = 'audio/webm'): string {
	return contentType.includes('mp4') ? 'm4a' : contentType.includes('ogg') ? 'ogg' : 'webm';
}

/** The inverse of audioExtension, for serving a file whose session predates the stored type. */
export function audioTypeForKey(key: string): string {
	if (key.endsWith('.m4a')) return 'audio/mp4';
	if (key.endsWith('.ogg')) return 'audio/ogg';
	return 'audio/webm';
}

// e.g. audio/webm;codecs=opus or audio/mp4. A stored type is echoed back as the
// Content-Type of the recording, on the app's own origin, so it is never taken
// from a multipart guess or an import archive without passing this.
const AUDIO_TYPE = /^audio\/[A-Za-z0-9.+-]+(;[\w=.\- ]+)?$/;

/** True for a MIME type this app is willing to store and serve for a recording. */
export function isAudioType(value: unknown): value is string {
	return typeof value === 'string' && value.length <= 100 && AUDIO_TYPE.test(value);
}

export function generateAudioKey(sessionId: string, contentType = 'audio/webm'): string {
	// The local calendar day, like practice days and the streak: a take at
	// 00:30 belongs to the evening it was recorded on, not to UTC's yesterday.
	const date = localDayKey(new Date());
	// UUIDv7 is time-ordered, so keys within a day still list chronologically.
	return `sessions/${date}/${sessionId}/${Bun.randomUUIDv7()}.${audioExtension(contentType)}`;
}

const KEY_SEGMENT = /^[A-Za-z0-9._-]+$/;

/**
 * True for the keys this module generates: relative, forward-slash separated,
 * no empty, `.` or `..` segments, nothing outside [A-Za-z0-9._-].
 */
export function isSafeAudioKey(key: string): boolean {
	if (!key || key.length > 512) return false;
	const segments = key.split('/');
	return segments.every((s) => KEY_SEGMENT.test(s) && s !== '.' && s !== '..');
}

function pathFor(key: string): string {
	if (!isSafeAudioKey(key)) throw new Error(`Refusing unsafe audio key: ${JSON.stringify(key)}`);
	const root = audioRoot();
	const path = resolve(root, key);
	// Belt and braces: the segment check above already rules this out.
	if (!path.startsWith(root + sep)) throw new Error(`Audio key escapes the audio directory`);
	return path;
}

export async function uploadAudio(
	key: string,
	data: ArrayBuffer | Uint8Array,
	// Kept for the callers' sake; the type is carried by the key's extension.
	_contentType: string
): Promise<string> {
	const path = pathFor(key);
	await mkdir(dirname(path), { recursive: true });
	await Bun.write(path, data);
	return key;
}

/** Copy a recording in from a file on disk (an extracted export). */
export async function importAudio(key: string, fromPath: string): Promise<string> {
	const path = pathFor(key);
	await mkdir(dirname(path), { recursive: true });
	await Bun.write(path, Bun.file(fromPath));
	return key;
}

/** Remove a recording. Missing files are not an error, matching S3 semantics. */
export async function deleteAudio(key: string): Promise<void> {
	if (!isSafeAudioKey(key)) return;
	const path = pathFor(key);
	await rm(path, { force: true });
	// Keys are sessions/<date>/<session>/<file>: the per-session directory is
	// this recording's alone, so it goes too. The date directory is shared and
	// stays; rmdir refuses anything that still has contents.
	const dir = dirname(path);
	if (dir !== audioRoot() && dirname(dir) !== audioRoot()) {
		await rmdir(dir).catch(() => {});
	}
}

/**
 * Copy a stored recording to a local path. Returns false if the file does not
 * exist, so an export can carry on and note the gap in its manifest.
 */
export async function downloadAudio(key: string, toPath: string): Promise<boolean> {
	if (!isSafeAudioKey(key)) return false;
	const file = Bun.file(pathFor(key));
	if (!(await file.exists())) return false;
	await Bun.write(toPath, file);
	return true;
}

export interface AudioObject {
	size: number;
	type: string;
	/** Whole file, or a byte range of it. `end` is inclusive. */
	stream(start?: number, end?: number): ReadableStream;
}

/**
 * Open a stored recording for streaming. Returns null if the file does not
 * exist, which is how sessions saved without audio ('placeholder-audio-key')
 * present as well.
 */
export async function openAudio(key: string): Promise<AudioObject | null> {
	if (!isSafeAudioKey(key)) return null;
	const path = pathFor(key);
	let size: number;
	try {
		const info = await stat(path);
		if (!info.isFile()) return null;
		size = info.size;
	} catch {
		return null;
	}
	return {
		size,
		type: audioTypeForKey(key),
		// Ranges go through node:fs rather than Bun.file().slice(): as of Bun 1.4.0
		// a file written by Bun.write in the same process streams its whole
		// contents regardless of the slice bounds (see TODO.md, waiting on upstream).
		stream: (start, end) =>
			start === undefined
				? Bun.file(path).stream()
				: (Readable.toWeb(
						createReadStream(path, { start, end: end ?? size - 1 })
					) as unknown as ReadableStream)
	};
}

/** Create the audio directory so the first upload does not have to. */
export async function ensureAudioDir(): Promise<void> {
	await mkdir(audioRoot(), { recursive: true });
}
